### Numpy arrays

Array creation

In [2]:
import numpy as np

In [111]:
a = np.array([1, 2, 3, 4])            
b = np.array([[1.,2.,3.,4.],[5.,6.,7.,8.]])   #remember the comma delimiters between 1D arrays
c = np.array([[[1,2,3,4],[5,6,7,8]],
              [[9,10,11,12],[13,14,15,16]]])

Type to find the data structure, shape to find out the rank

In [31]:
print(type(a), a.shape, a.dtype)

print(type(b), b.shape, b.dtype)

print(type(c), c.shape, c.dtype) # Note how the z dimension shows up first

print("\n", c)

print("\n", c[1,:,:])

print("\n", c[:,:,1])

<class 'numpy.ndarray'> (4,) int64
<class 'numpy.ndarray'> (2, 4) float64
<class 'numpy.ndarray'> (2, 2, 4) int64

 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

 [[ 9 10 11 12]
 [13 14 15 16]]

 [[ 2  6]
 [10 14]]


Other useful array attributes

In [5]:
print(a.ndim, a.size)
print(b.ndim, b.size)
print(c.ndim, c.size)

1 4
2 8
3 16


Other ways of creating arrays

In [6]:
arrj = np.zeros((3,2))
print(arrj, "\n")

arrk = np.ones((2,4))
print(arrk, "\n")

arrl = np.zeros_like(arrk)
print(arrl, "\n")

arrm = np.random.random((3,3))
print(arrm, "\n")

arrm = np.arange(12)  #takes scalar argument and returns an 1D - array
print(type(arrm), arrm.shape, arrm, "\n")

# use linspace instead of arange this to clearly specify no. of points you want 
arrn = np.linspace(0,11,13) #linspace(start_no, stop_no, No.of points)
print(type(arrn), arrn.shape, arrn, "\n")

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] 

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] 

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] 

[[ 0.22442023  0.85840773  0.62110909]
 [ 0.19705851  0.37639728  0.27102779]
 [ 0.51487417  0.79111208  0.36779638]] 

<class 'numpy.ndarray'> (12,) [ 0  1  2  3  4  5  6  7  8  9 10 11] 

<class 'numpy.ndarray'> (13,) [  0.           0.91666667   1.83333333   2.75         3.66666667
   4.58333333   5.5          6.41666667   7.33333333   8.25         9.16666667
  10.08333333  11.        ] 



In [7]:
# easy to change datatypes by using the astype function on the array
print(arrm)

arrm.astype(float)

print("\n", arrm)


[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]


All arithmetic and comparison operations on arrays in numpy are elemenwise operations, not matrix operations

In [8]:
d = np.array([[1,1,1,1],[2,2,2,2]])

In [9]:
print(b + d)   # Note element wise addition and automatic data type conversion 

[[  2.   3.   4.   5.]
 [  7.   8.   9.  10.]]


In [10]:
print(b * d)  #Element wise multiplication, not matrix multiplication - For matrix multiplication, use the dot operator

[[  1.   2.   3.   4.]
 [ 10.  12.  14.  16.]]


In [11]:
print(b,"\n\n",d)
print("\n",b > (d+2))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]] 

 [[1 1 1 1]
 [2 2 2 2]]

 [[False False False  True]
 [ True  True  True  True]]


In [12]:
print(b[b > (d+2)], b[b > (d+2)].shape)  # Note shape of the original array is not preserved, you get a 1D array 

[ 4.  5.  6.  7.  8.] (5,)


### Reshaping arrays

In [13]:
x = np.ravel(d)               #If you want to flatten the array into a 1D array
print(type(x), x.shape, x)

<class 'numpy.ndarray'> (8,) [1 1 1 1 2 2 2 2]


In [14]:
m = np.reshape(x,(2,2,2))
print(x,"\n\n", m)
n = np.resize(x, (2,4))
print("\n\n",x,"\n\n", n)
# So what is the difference between both of these funtions

[1 1 1 1 2 2 2 2] 

 [[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]]


 [1 1 1 1 2 2 2 2] 

 [[1 1 1 1]
 [2 2 2 2]]


In [15]:
## Difference - reshape makes a copy and reshapes whereas resize does it in-place (note that n is none)
print(x)
m = x.reshape((2,1,4))
print ("\n",x,"\n\n", m)

print("\n\n",x)
n = x.resize((4,2))
print("\n\n",x,"\n\n", n)


[1 1 1 1 2 2 2 2]

 [1 1 1 1 2 2 2 2] 

 [[[1 1 1 1]]

 [[2 2 2 2]]]


 [1 1 1 1 2 2 2 2]


 [[1 1]
 [1 1]
 [2 2]
 [2 2]] 

 None


In [135]:
## most indexing reduces shape of the array, we can reduce or increase the dimensions of the array as follows

temp = np.array([[[1,2],[2,3]]])

print(temp.shape)
print('\n')
print(temp)
print('\n')

temp = np.squeeze(temp)

print(temp.shape)
print('\n')
print(temp)
print('\n')

temp = np.expand_dims(temp,0)
print(temp.shape)
print('\n')
print(temp)
print('\n')

(1, 2, 2)


[[[1 2]
  [2 3]]]


(2, 2)


[[1 2]
 [2 3]]


(1, 2, 2)


[[[1 2]
  [2 3]]]




### Slicing & Indexing

In [34]:
b = np.array([[1.,2.,3.,4.],[5.,6.,7.,8.]])

print(b, b.shape)

print("\n",b[:,1])
print("\n",b[1,:])

c = b[1,:]

print("\n", c, c.shape)  #Note that slicing reduces the array dimensions


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]] (2, 4)

 [ 2.  6.]

 [ 5.  6.  7.  8.]

 [ 5.  6.  7.  8.] (4,)


In [36]:
c[1] = 666
print("\n", c, c.shape)

print("\n", b, b.shape)   #### Modifying slice modifies the original array too


 [   5.  666.    7.    8.] (4,)

 [[   1.    2.    3.    4.]
 [   5.  666.    7.    8.]] (2, 4)


In [43]:
## You have to make a copy to avoid slicing to not overwrite the original
## Note that explicit copy, not 

b = np.array([[1.,2.,3.,4.],[5.,6.,7.,8.]])

print(b, b.shape)

print("\n",b[:,1])
print("\n",b[1,:])

c = b  ### This is not a copy, changes in C are reflected in source array b

c[1,2] = 888
print("\n", c, c.shape)  #Note that slicing reduces the array dimensions
print("\n", b, b.shape)


## Copy of the original array needs to be made explicity with copy function

d = np.copy(b)

d[1,3] = 1000             #Change does not reflect in source array b
print("\n", d, d.shape)  
print("\n", b, b.shape)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]] (2, 4)

 [ 2.  6.]

 [ 5.  6.  7.  8.]

 [[   1.    2.    3.    4.]
 [   5.    6.  888.    8.]] (2, 4)

 [[   1.    2.    3.    4.]
 [   5.    6.  888.    8.]] (2, 4)

 [[    1.     2.     3.     4.]
 [    5.     6.   888.  1000.]] (2, 4)

 [[   1.    2.    3.    4.]
 [   5.    6.  888.    8.]] (2, 4)


In [65]:
print(d)
print ("\n")

print(d[:,-1])  # -1 refers to the last index
print("\n")

## slicing allows to select ranges for each index

print(d[:,1:2])
print("\n")

print(d[:,:-1]) # :-1 is the same as 0:-1 starting index to last index (exclusive)
print("\n")

orig = np.array([[1,2], [2,3],[3,4]])

print(orig)
print("\n")
print(orig[:,::-1]) # reverses the 2D array along the second dimension

print("\n")
print(orig[::-1,:]) # reverses the 2D array along the first dimension

## Note that images can be converted from RGB to BGR by flipping the third dimension. for ex. arr[:,:,::-1] 

[[    1.     2.     3.     4.]
 [    5.     6.   888.  1000.]]


[    4.  1000.]


[[ 2.]
 [ 6.]]


[[   1.    2.    3.]
 [   5.    6.  888.]]


[[1 2]
 [2 3]
 [3 4]]


[[2 1]
 [3 2]
 [4 3]]


[[3 4]
 [2 3]
 [1 2]]


### Indexing in arrays

In [106]:
a = np.arange(15).reshape(3,5)

print(a)
print('\n')

print(a)
print("\n")

## find the indices of elements which is an even number
print((a%2 == 0))
a_val = ((a%2)==0).nonzero()
print("\n")
print(a_val[0], a_val[1])
print("\n")

## find the indices of elements which is an even number and assign them to a value of -1
a[a%2 == 0] = -1
print(a)
print("\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


[0 0 0 1 1 2 2 2] [0 2 4 1 3 0 2 4]


[[-1  1 -1  3 -1]
 [ 5 -1  7 -1  9]
 [-1 11 -1 13 -1]]




### Python

In [107]:
#enumerate - lets you get count and the actual element at the same time
a = ['apple', 'boy', 'cat', 'dog']

for i, word in enumerate(a):
    print("Count %d, Word is %s"%(i,word)) 

Count 0, Word is apple
Count 1, Word is boy
Count 2, Word is cat
Count 3, Word is dog


In [108]:
## Zip - If you do not want to iterate through all combinations of lists, but only through equivalent locations 
x = [1, 4, 6, 9]
y = [10, 11, 12, 13]

for i in zip(x,y):
    print(i, i[0], i[1])

(1, 10) 1 10
(4, 11) 4 11
(6, 12) 6 12
(9, 13) 9 13
